### PR TITLE
Semiring and records

### PR DESCRIPTION
**Pull request by anttih**
Implement FFI for

* Record.Unsafe
* Data.Semiring

### CODE REVIEW

**Review by f-f — APPROVED** [review]

**Comment by f-f** [comment]
I guess we'll need to fix CI to make it meaningful 😄

**Comment by anttih** [comment]
I can't merge this. Can you @f-f?

**Comment by f-f** [comment]
I merged it, but I thought that giving you access to the org would give you more permissions. I'll have a look at them

**Comment by f-f** [comment]
Permissions should be fixed now

**Pull request merged**
